version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db_test
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    restart: always
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data_test:
